/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: HallowDragon (https://sketchfab.com/HallowDragon)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/dragon-boss-d5e3aeefab2245cdad78ec3463dab005
Title: Dragon Boss
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import dragonscene from "../assets/3d/dragon_boss.glb";
import { a } from "@react-spring/three";
const Dragon = ({ currentanimations, ...props }) => {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(dragonscene);
  const { actions } = useAnimations(animations, group);

  useEffect(() => {
    Object.values(actions).forEach((action) => action.stop());
    //actions = actions.map((action) => action.stop());
    if (actions[currentanimations]) {
      actions[currentanimations].play();
    }
  }, [actions, currentanimations]);
  return (
    <a.group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.997}
        >
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group
                name="Sketchfab_model_0"
                rotation={[-Math.PI / 2, 0, 0]}
                scale={46.949}
              >
                <group
                  name="Dragon_Boss_05fbx_1"
                  rotation={[Math.PI / 2, 0, 0]}
                  scale={0.01}
                >
                  <group name="Object_2_2">
                    <group name="RootNode_3">
                      <group name="Dragon_Boss_05_4">
                        <group name="Object_5_5">
                          <group name="GLTF_created_0">
                            <primitive
                              object={nodes.GLTF_created_0_rootJoint}
                            />
                            <skinnedMesh
                              name="Object_82"
                              geometry={nodes.Object_82.geometry}
                              material={materials.Dragon_Boss_05}
                              skeleton={nodes.Object_82.skeleton}
                            />
                            <group name="Object_8_8_correction">
                              <group name="Object_8_8" />
                            </group>
                          </group>
                        </group>
                      </group>
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </a.group>
  );
};

export default Dragon;
